### ISSUE TITLE
recent episode

### ISSUE THREAD

**Issue by Pacifierjr** [Enime-Project/api.enime.moe#9]
Hi, id like to ask why the recent episode is not accurate? i mean the lists.
because as i see on source you use goload.io and zoro.to but the recent episode lists is not the same. hehe

**Comment by riimuru** [comment]
@Pacifierjr looks right to me. What seems off?

**Comment by NADESHIKON** [comment]
@Pacifierjr In order to implement “true recent episodes” feature, the recent episode route from Enime API does not depend on when Gogoanime or Zoro uploaded these episodes - they’re merely source providers and will not have any other use for the system. 

Instead, the system utilizes other “meta providers” to fetch the airing time for these uploaded episodes and sort them for recent episodes. This has some flaws
1. Sometimes the meta providers mess up the air time but that’s rare
2. Sometimes the ID mapping to meta providers does not exist, causes airing time to be always null which places those entires last for the recent route

The solution to this issue is to add more meta providers for more information coverag, which I’m planning to do in the future. For example, I’ll start to implement TmDB once this project reaches 50 stars.

**Comment by Pacifierjr** [comment]
> @Pacifierjr looks right to me.

i mean sir. i hope the recent episode is like on goload.io and zoro.to
example the last episode update on goload and zoro is "Orient" Episode 8
so its looks good than it's look like shuffle hehe

**Comment by riimuru** [comment]
> > @Pacifierjr looks right to me.
> 
> i mean sir. i hope the recent episode is like on goload.io and zoro.to
> example the last episode update on goload and zoro is "Orient" Episode 8
> so its looks good than it's look like shuffle hehe

Ur welcome to use https://github.com/consumet/consumet-api

**Comment by Pacifierjr** [comment]
also brothers, can i ask if this api is for raw and subbed only? because when i check the https://enime.moe/ base on this api. there is no dub found hehe

**Comment by Pacifierjr** [comment]
also brothers, can i ask if this api is for raw and subbed only? because when i check the https://enime.moe/ base on this api. there is no dub found hehe

**Comment by NADESHIKON** [comment]
> also brothers, can i ask if this api is for raw and subbed only? because when i check the https://enime.moe/ base on this api. there is no dub found hehe

Yes it’s sub only, I have no plans for dubs because
1. I don’t use dubs myself
2. People should abandon subs in my opinion

**Comment by Pacifierjr** [comment]
> > also brothers, can i ask if this api is for raw and subbed only? because when i check the https://enime.moe/ base on this api. there is no dub found hehe
> 
> Yes it’s sub only, I have no plans for dubs because
> 
> 1. I don’t use dubs myself
> 2. People should abandon dubs in my opinion

i see i understand. thanks for the answer brother hehe
but i hope in the future it having on api only for those want to use this api that want dub also hehe
